services:
  stream-alert:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-alert
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"